server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zycCome/microservicecloud-config.git
          search-paths: app1 # 目录名
          username: xx
          password: xx
      label: master
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-config-1
    prefer-ip-address: true     #访问路径可以显示IP地址
    hostname: config1.com